[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/portfolio/berakhot"
  to = "/portfolio/jewish-journey"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
